version: '3.3'

services:
  db:
    image: postgres:11
    ports: 
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - type: bind
        source: ./chinook_data.sql
        target: /docker-entrypoint-initdb.d/chinook_data.sql
    restart: always
    environment:
      -  POSTGRES_USER=vagrant
      -  POSTGRES_PASSWORD=vagrant
      -  POSTGRES_DB=chinook
volumes:
  db_data: